ReplicatedSuiteModuleSandbox:Enter('healer', {'ReplicatedHealerBoot', 'ReplicatedHealerConfig', 'ReplicatedHealerModule'})
-----------------------------------------------------------------------
-- Replicated Healer - Shareable defaults / persistence namespace
-- Author: Replicated
-- Personal runtime configuration is kept by ADDON:SaveData, not in this file.
-----------------------------------------------------------------------

ReplicatedHealerConfig = {
    SaveKey = "replicated_healer_recommender_v2",
    LegacySaveKey = "replicated_healer_recommender_v1",
    SettingsVersion = 222,
    Defaults = {
	settingsVersion = 222,
	enabled = false,
	panelMode = 1,
	recommendSortMode = 1,
	recommendDetailed = false,
	fullRecommendCount = 10,
	miniRecommendCount = 3,
	headMarkerCount = 5,
	maxDistance = 27,
	enterThreshold = 100,
	exitThreshold = 100,
	selfThreshold = 70,
	emergencyThreshold = 50,
	lowHealthThreshold = 70,
	minHoldMs = 500,
	scoreLead = 5,
	healthScanMs = 100,
	buffScanMs = 200,
	weights = { health = 55, distance = 15, missing = 10, unprotected = 20 },
	healthCurveMode = 2,
	healthAccelMode = 2,
	distanceCurveMode = 2,
	distanceEdgePercent = 20,
	missingSensitivity = 30000,
	levelThresholds = { attention = 40, high = 60, emergency = 80 },
	levelColors = {
		{ r = 1.00, g = 0.48, b = 0.08, a = 0.60 },
		{ r = 1.00, g = 0.48, b = 0.08, a = 0.72 },
		{ r = 1.00, g = 0.12, b = 0.12, a = 0.80 },
		{ r = 1.00, g = 0.08, b = 0.08, a = 0.92 },
	},
	raidEffectMode = 1,
	headEffectMode = 1,
	headShapeMode = 4,
	headSizes = { 18, 24, 30, 36 },
	showHeadName = false,
	showHeadDistance = false,
	showHeadScore = false,
	showRaidRanks = true,
	raidRankCount = 10,
	raidRankFontSize = 10,
	raidRankAlpha = 1,
	raidRankCorner = 2,
	raidRankOffsetX = 1,
	raidRankOffsetY = 1,
	roleScoringEnabled = false,
	roleScores = { normal = 0, mainTank = 15, offTank = 10, healer = 8, unknown = 0 },
	roleOverrides = {},
	rules = { {
        name = "持续回血",
        enabled = true,
        purpose = 1,
        sourceMode = 1,
        matchMode = 1,
        ids = { 25875, 220 },
        minStacks = 1,
        minRemainingMs = 0,
        unknownRemainingValid = true,
        healthRangeEnabled = false,
        healthMin = 0,
        healthMax = 100,
        effectType = 1,
        scoreMode = 2,
        scoreValue = 25,
        allowStack = false,
        emergencyRetainPercent = 20,
        countsAsProtection = true,
        displayPriority = 10,
        rescuePriority = 50,
        color = { r = 0.72, g = 0.30, b = 1.00, a = 0.82 },
        distanceMode = 1,
        customDistance = 27,
        healPriorityThreshold = 70,
        excludeDisplayMode = 1,
    } },
	panelAnchor = { horizontal = "LEFT", vertical = "TOP", offsetX = 420, offsetY = 190 },
	recommendWidth = 510,
	recommendHeight = 342,
	configAnchor = { horizontal = "LEFT", vertical = "TOP", offsetX = 360, offsetY = 120 },
	launcherAnchor = { horizontal = "LEFT", vertical = "TOP", offsetX = 300, offsetY = 100 },
	launcherImplementation = "bootstrap_v22_left_safe",
	pageSwitcherAnchor = { horizontal = "LEFT", vertical = "TOP", offsetX = 0, offsetY = 145 },
	raidOverlayTop = { horizontal = "LEFT", vertical = "TOP", offsetX = 0, offsetY = 140, width = 340, height = 196 },
	raidOverlayBottom = { horizontal = "LEFT", vertical = "TOP", offsetX = 0, offsetY = 344, width = 340, height = 196 },
	raidOverlayTopRaid2 = { horizontal = "LEFT", vertical = "TOP", offsetX = 360, offsetY = 140, width = 340, height = 196 },
	raidOverlayBottomRaid2 = { horizontal = "LEFT", vertical = "TOP", offsetX = 360, offsetY = 344, width = 340, height = 196 },
	raidCalibrationSection = 1,
	raidCalibrationScope = 1, -- 1=两团, 2=仅1团, 3=仅2团
	proximityMode = true,
	proximityDistance = 27,
	-- Visual priority: emergency > tracked Buff > low health > in-range base.
	-- Colors are stored normalized (0..1) but edited as RGB 0..255 + Alpha %.
	proximityColor = { r = 1.00, g = 0.42, b = 0.68, a = 0.42 }, -- pink
	lowHealthColor = { r = 1.00, g = 0.48, b = 0.08, a = 0.78 }, -- orange
	emergencyColor = { r = 1.00, g = 0.08, b = 0.08, a = 0.92 }, -- red
	trackedBuffs = {
		{ id = 25875, name = "持续回血", enabled = true, color = { r = 0.72, g = 0.30, b = 1.00, a = 0.84 } },
		{ id = 220, name = "持续回血", enabled = true, color = { r = 0.72, g = 0.30, b = 1.00, a = 0.84 } },
	},
	manualRaidPage = 1,
	manualRaidPageLocked = false,
	settingsPage = 1,
    },
}
