ADDON:
ImportAPI(apiType)
ImportObject(objectType)
RegisterContentWidget(uiCategory)
RegisterContentTriggerFunc(uiCategory)
GetContent(uiCategory)
GetContentMainScriptPosVis(uiCategory)
ShowContent(uiCategory, arg)
ToggleContent(uiCategory)
GetAddonInfos()
SetAddonEnable(name, enable)
SaveAddonInfos()
FireAddon(name)
ReloadAddon(name)
ChatLog(logMessage)
GetName()
LoadData(key)
SaveData(key, table)
ClearData(key)
AddEscMenuButton(categoryId, uiContentType, iconKey, name)
-------
Console:
GetAttribute(attr)
ExecuteString(str)
-------
UI:
CreateWidget()
GetScreenWidth()
GetScreenHeight()
GetVirtualMemoryStats()
GetCurrentDP()
GetCurrentPolyCount()
IsDX11Supported()
IsRenderThreadSupported()
GetFrameTime()
GetFrameRate()
GetViewCameraPos()
GetViewCameraDir()
GetViewCameraAngles()
GetUIScaleRange()
GetUIScale()
SetUIScale(scale, immediatelyApply)
SetViewCameraFov(fov)
SetViewCameraPos(pos)
SetViewCameraDir(dir)
SetViewCameraAngles(angles)
GetViewCameraFov()
IsPointVisible(point)
GetEntityByName(sEntityName)
SetUseInsertComma(use)
SetEventHandler(eventName, handler)
ReleaseEventHandler(eventName, handler)
GetUIStamp(key)
GetCurrentTimeStamp()
GetAccountUITimeStamp(key)
GetCharacterTodayPlayedTimeStamp()
GetServerTimeTable()
GetTextureKeyData(filename)
GetTextureData(filename, infoKey)
GetFontColor(key)
GetEtcValue(key)
GetUIBound(key)
SetUIBound(key, table)
ClearUIBound(key)
GetPermission(category)
InitFontSize()
GetId()
-------
X2Ability:
GetActiveAbility()
IsActiveAbility(index)
GetBuffTooltip(buffType, itemLevel)
GetAllMyActabilityInfos()
GetMyActabilityInfo(actAbilityGroupType)
-------
X2Achievement:
GetAchievementName(type)
GetCategories(kind)
GetSubcategoryInfo(subCategory)
GetCategoryCount(kind, cType, scType, filter)
GetAchievementTracingList(kind)
GetAchievementMainList(kind, sId, filter)
GetAchievementSubList(mainType, filter)
GetAchievementInfo(aId)
AddTracingAchievement(aId, inLevel)
RemoveTracingAchievement(aId, inLevel)
IsTracingAchievement(aId, inLevel)
GetTodayAssignmentInfo(todayType, index)
GetTodayAssignmentInfoForChange(todayType, index)
GetTodayAssignmentCount(todayType)
GetTodayAssignmentGoal()
GetTodayAssignmentStatus()
IsTodayAssignmentQuest(todayType, questType)
GetTodayAssignmentResetCount(todayType)
-------
X2Auction:
SearchAuctionArticle(page, minLevel, maxLevel, grade, category, exactMatch, keywords, minDirectPriceStr, maxDirectPriceStr)
GetSearchedItemPage()
GetSearchedItemCount()
GetSearchedItemTotalCount()
GetSearchedItemInfo(idx)
GetLowestPrice(itemType, itemGrade)
AskMarketPrice(itemType, itemGrade, askMarketPriceUi)
-------
X2Chat:
DispatchChatMessage(filter, message)
-------
X2CombatResource:
GetCombatResourceInfo()
GetCombatResourceInfoByGroupType(groupType)
CheckCombatResourceMaxPointByGroupType(groupType)
-------
X2Craft:
GetCraftBaseInfo(craftType)
GetCraftMaterialInfo(craftType, doodadId)
GetCraftProductInfo(craftType)
-------
X2Equipment:
MateUnequipItem(unit, equipSlot)
PickupMateEquippedItem(unit, equipSlot)
GetEquippedItemTooltipInfo(equipSlot, targetEquippedItem)
GetEquippedItemType(equipSlot)
-------
X2Hotkey:
SaveHotKey()
BindingToOption()
OptionToBinding()
GetOptionBinding(action, index, option, arg)
GetOptionBindingButton(buttonName, index)
SetOptionBindingButtonWithIndex(buttonName, key)
SetOptionBindingWithIndex(action, key, index, arg)
EnableHotkey(enable)
IsValidActionName(action)
IsOverridableAction(action)
GetBindingUiEvent(actionName, index)
SetBindingUiEvent(actionName, key)
SetBindingUiEventWithIndex(actionName, key, index)
GetOptionBindingUiEvent(actionName, index)
SetOptionBindingUiEvent(actionName, key)
SetOptionBindingUiEventWithIndex(actionName, key)
-------
X2Item:
InfoFromLink(linkText)
-------
X2Locale:
HasLocalizeUiText()
LocalizeUiText()
LocalizeFormatUiText()
TextFormating(text)
GetLocale()
GetLocaleIndex()
GetKeyboardLayout()
LocalizeNonUiText()
-------
X2Player:
GetUnitAppellationRouteList()
GetAppellationCount()
GetAppellations(routeFilter, keyword, pageIndex)
GetAppellationsCount(routeFilter, keyword)
ChangeAppellation(nameType, effectType)
GetShowingAppellation()
GetEffectAppellation()
GetAppellationMyLevelInfo()
GetAppellationBuffInfoByLevels()
GetAppellationRouteInfo(type)
GetAppellationStampInfos()
GetAppellationStampInfo(stampId)
GetAppellationMyStamp()
GetAppellationChangeItemInfo()
GetStampChangeItemInfo()
-------
X2Quest:
GetQuestContextMainTitle(type)
SetTrackingActiveQuest(idx)
GetActiveQuestListCount()
GetActiveQuestType(idx)
IsCompleted(type)
-------
X2Resident:
RefreshResidentMembers(zoneGroupType, bool, int)
GetResidentMembers(zoneGroupType, bool, int)
RequestHousingTradeList(zoneGroupType, filterindex, searchWord)
FilterHousingTradeList(filterindex, searchWord)
GetResidentBoardContent(boardType)
-------
X2SiegeWeapon:
GetSiegeWeaponSpeed()
GetSiegeWeaponTurnSpeed()
-------
X2Skill:
GetSkillTooltip(skillId, itemType)
Info(skillId)
GetCooldown(skillId, ignoreGlobalCooldown)
GetMateCooldown(skillId, ignoreGlobalCooldown, mateType)
-------
X2Sound:
PlayUISound(soundPackItemName)
IsPlaying(soundId)
StopSound(soundId)
PlayMusic(soundPackItemName)
StopMusic()
-------
X2Store:
GetSpecialtyRatio()
GetZoneSpecialtyRatio()
GetSpecialtyRatioBetween(fromZoneGroup, toZoneGroup)
GetProductionZoneGroups()
GetSellableZoneGroups(fromZoneGroup)
-------
X2Team:
GetRole(teamIndex, memberIndex)
SetRole(role)
-------
X2Time:
GetGameTime()
GetServerTime()
-------
X2Unit:
GetUnitId(unit)
UnitName(unit)
UnitNameWithWorld(unit)
UnitHealth(unit)
UnitMaxHealth(unit)
UnitHealthInfo(unit)
UnitMana(unit)
UnitMaxMana(unit)
UnitManaInfo(unit)
UnitLevel(unit)
UnitCastingInfo(unit)
UnitDistance(unit)
UnitGearScore(unit, comma)
UnitBuffTooltip(unit, buffIndex)
UnitBuff(unit, buffIndex)
UnitBuffCount(unit)
UnitDeBuff(unit, buffIndex)
UnitDeBuffCount(unit)
UnitDeBuffTooltip(unit, buffIndex)
UnitHiddenBuff(unit, buffIndex)
UnitHiddenBuffCount(unit)
UnitHiddenBuffTooltip(unit, buffIndex)
UnitRemovableDebuffTooltip(unit, buffIndex)
UnitRemovableDebuff(unit, buffIndex)
UnitRemovableDebuffCount(unit)
GetUnitWorldPositionByTarget(unit, isLocal)
GetUnitScreenPosition(unit)
GetTargetAbilityTemplates(target)
GetTargetUnitId()
GetUnitNameById(stringId)
GetUnitInfoById(stringId)
GetCurrentZoneGroup()
-------
