-- ArcheRage RU addon API capability overlay
-- Updated through 2026-08-28.
-- status reflects official announcements; runtime_verified=false means the project has not yet
-- independently sampled the function on the current client in this update pass.
return {
  meta = {
    updated = "2026-08-28",
    server = "ArcheRage RU",
    policy = "official announcements overlay bundled snapshot; runtime evidence may override for safety",
  },

  changes = {
    ["2025-04-29"] = {
      { api="X2Craft:GetCraftBaseInfo", status="official_enabled" },
      { api="X2Craft:GetCraftMaterialInfo", status="official_enabled", note="Later fixed for client crash on 2026-06-02." },
      { api="X2Craft:GetCraftProductInfo", status="official_enabled" },
    },
    ["2026-02-24"] = {
      { api="X2Team:MoveTeamMember", status="official_enabled", cooldown_ms=1000 },
      { api="X2Team:MoveTeamMemberToParty", status="official_enabled", cooldown_ms=1000 },
      { api="X2Team:KickTeamMember", status="official_enabled", cooldown_ms=1000 },
      { api="X2Team:KickTeamMemberByName", status="official_enabled", cooldown_ms=1000 },
      { api="X2Team:GetTeamRoleType", status="official_enabled" },
    },
    ["2026-03-24"] = {
      { api="X2Unit:SetOverHeadMarker", status="official_enabled", cooldown_ms=1000 },
      { api="X2Unit:RemoveAllOverHeadMarker", status="official_enabled", cooldown_ms=1000 },
      { api="X2Unit:GetOverHeadMarker", status="official_enabled" },
      { api="X2Unit:GetOverHeadMarkerUnitId", status="official_enabled" },
    },
    ["2026-03-31"] = {
      { api="X2Quest:IsReadyForCompleteQuest", status="official_enabled" },
      { api="ADDON:UpdateEscMenuButton", status="official_enabled", note="Official post uses X2 namespace wording; bundled client/project uses ADDON for Esc menu API." },
      { api="ADDON:AddEscMenuButton", status="official_changed", note="Official post added an optional config table (buttonType/buttonValue/colorKey). Keep tested 4-arg form compatible." },
    },
    ["2026-04-07"] = {
      { api="X2Team:RaidRecruitAdd", status="official_enabled", cooldown_ms=5000 },
      { api="X2Team:RaidRecruitDel", status="official_enabled", cooldown_ms=5000 },
      { api="X2Bag:GetBagItemInfo", status="official_enabled", note="Official April wording lists slot; older official/bundled ArcheRage form uses bagId,slot. Preserve tested bundled signature." },
      { api="X2Bag:CountItems", status="official_enabled" },
      { api="X2Bag:ItemStack", status="official_enabled" },
      { api="X2Bank:GetBagItemInfo", status="official_enabled" },
      { api="X2Bank:CountItems", status="official_enabled" },
      { api="X2Bank:ItemStack", status="official_enabled" },
      { api="X2GuildBank:GetBagItemInfo", status="official_enabled" },
      { api="X2GuildBank:CountItems", status="official_enabled" },
      { api="X2GuildBank:ItemStack", status="official_enabled" },
      { api="X2Coffer:GetBagItemInfo", status="official_enabled" },
      { api="X2Coffer:CountItems", status="official_enabled" },
      { api="X2Coffer:ItemStack", status="official_enabled" },
    },
    ["2026-04-28"] = {
      { api="X2EquipSlotReinforce:*listed_getters", status="official_enabled", note="20 reinforcement query functions moved to Allowed; see api_functions.lua." },
      { api="X2Friend:IsMyFriend", status="official_enabled" },
      { api="X2Friend:GetFriendList", status="official_enabled" },
      { api="X2Family:GetMemberList", status="official_enabled" },
      { api="X2Faction:IsMyExpeditionMember", status="official_enabled" },
    },
    ["2026-05-12"] = {
      { api="X2Bag:MoveToEmptyBankSlot", status="official_enabled", cooldown_ms=500, note="Later fixed on 2026-05-19 and again 2026-06-02 for intermittent behavior." },
      { api="X2Bag:MoveToEmptyCofferSlot", status="official_enabled", cooldown_ms=500, note="Later fixed on 2026-05-19." },
      { api="X2Coffer:MoveToEmptyBagSlot", status="official_enabled", cooldown_ms=500, note="Later fixed on 2026-05-19." },
      { api="X2Bank:MoveToEmptyBagSlot", status="official_enabled", cooldown_ms=500, note="Later fixed on 2026-05-19 and 2026-06-02 for intermittent behavior." },
      { api="X2Bag:Capacity", status="official_enabled" },
      { api="X2Coffer:Capacity", status="official_enabled" },
      { api="X2Bank:Capacity", status="official_enabled" },
      { api="X2Input:IsShiftKeyDown", status="official_enabled" },
      { api="X2Input:IsControlKeyDown", status="official_enabled" },
      { api="X2Input:IsAltKeyDown", status="official_enabled" },
      { api="X2Hotkey:RemoveOptionBinding", status="official_enabled", note="Official post spells namespace X2HotKey; bundled reference uses X2Hotkey." },
      { api="X2EquipSlotReinforce:GetLevelEffectChangeUIInfo", status="official_enabled_fixed_crash" },
      { api="X2EquipSlotReinforce:GetMaterialInfo", status="official_enabled_fixed_crash" },
    },
    ["2026-05-19"] = {
      { api="X2Bag:MoveToEmptyBankSlot", status="official_enabled_fixed", cooldown_ms=200, note="Window-open restriction fixed; cooldown reduced to 200ms." },
      { api="X2Bag:MoveToEmptyCofferSlot", status="official_enabled_fixed", cooldown_ms=200, note="Window-open restriction fixed; cooldown reduced to 200ms." },
      { api="X2Coffer:MoveToEmptyBagSlot", status="official_enabled_fixed", cooldown_ms=200, note="Window-open restriction fixed; cooldown reduced to 200ms." },
      { api="X2Bank:MoveToEmptyBagSlot", status="official_enabled_fixed", cooldown_ms=200, note="Window-open restriction fixed; cooldown reduced to 200ms." },
      { api="X2BattleField:GetInstanceUiKindList", status="official_enabled" },
      { api="X2BattleField:GetInstanceListByKind", status="official_enabled" },
      { api="X2BattleField:GetDetailInstanceInfo", status="official_enabled" },
      { api="X2BattleField:GetInstanceName", status="official_enabled" },
      { api="X2Squad:CreateSquad", status="official_enabled", cooldown_ms=5000 },
    },
    ["2026-05-26"] = {
      { api="X2World:GetCurrentWorldName", status="official_enabled" },
      { api="X2Bag:GetBagItemInfo", status="official_changed", note="Return info includes category_id." },
      { api="X2Bank:GetBagItemInfo", status="official_changed", note="Return info includes category_id." },
      { api="X2Coffer:GetBagItemInfo", status="official_changed", note="Return info includes category_id." },
    },
    ["2026-06-02"] = {
      { api="X2Craft:GetCraftMaterialInfo", status="official_fixed_crash", note="Official fix post abbreviates the signature; bundled reference keeps GetCraftMaterialInfo(craftType, doodadId)." },
      { api="X2Bag:MoveToEmptyBankSlot", status="official_enabled_fixed" },
      { api="X2Bank:MoveToEmptyBagSlot", status="official_enabled_fixed" },
      { api="X2Unit:UnitInfo", status="official_enabled" },
      { api="X2Unit:UnitModifierInfo", status="official_enabled" },
    },
    ["2026-06-09"] = {
      { api="X2Craft:GetCraftTypeByItemType", status="official_enabled" },
      { api="X2Player:PlayerInCombat", status="official_enabled" },
      { api="X2Player:ChangeAppellation", status="official_enabled_restricted", cooldown_ms=2000, combat_restricted=true },
      { api="X2Bag:EquipBagItem", status="official_enabled_restricted", combat_restricted=true },
      { api="X2Unit:GetUnitsInSight", status="official_enabled" },
      { api="UNIT_ENTERED_SIGHT", status="removed" },
      { api="UNIT_LEAVED_SIGHT", status="removed" },
    },
    ["2026-07-07"] = {
      { api="X2Chat:AddRaidRecruitLinkToActiveChatInput", status="official_enabled" },
      { api="X2Team:GetLinkText", status="official_enabled" },
      { api="X2Team:RaidApplicantList", status="official_enabled", cooldown_ms=1000 },
      { api="X2Team:RaidApplicantAccept", status="official_enabled", cooldown_ms=1000 },
      { api="X2Team:RaidApplicantReject", status="official_enabled", cooldown_ms=1000 },
    },
    ["2026-07-14"] = {
      { api="X2Team:MakeTeamOwner", status="official_enabled", cooldown_ms=5000 },
      { api="X2Team:RaidRecruitDel", status="official_changed", note="No confirmation required." },
    },
    ["2026-07-21"] = {
      { api="X2Team:InviteToTeam", status="official_enabled", cooldown_ms=1000 },
    },
    ["2026-08-05"] = {
      { api="X2Friend:GetBlockList", status="official_enabled" },
      { api="X2Friend:BlockUser", status="official_enabled", cooldown_ms=1000 },
      { api="X2Friend:UnblockUser", status="official_enabled", cooldown_ms=1000 },
      { api="X2Friend:GetMuteList", status="official_enabled" },
      { api="X2Friend:MuteUser", status="official_enabled", cooldown_ms=1000 },
      { api="X2Friend:UnmuteUser", status="official_enabled", cooldown_ms=1000 },
    },
    ["2026-08-19"] = {
      { api="X2Unit:GetUnitsInSight", status="official_disabled", note="Disabled by RU 2026-08-19 update; last-write-wins is Disabled." },
      { api="X2Hotkey:SaveHotKey", status="official_enabled_restricted", combat_restricted=true },
      { api="X2Hotkey:BindingToOption", status="official_enabled_restricted", combat_restricted=true },
      { api="X2Hotkey:OptionToBinding", status="official_enabled_restricted", combat_restricted=true },
      { api="X2Hotkey:RemoveOptionBinding", status="official_enabled_restricted", combat_restricted=true },
      { api="X2Hotkey:SetOptionBindingButtonWithIndex", status="official_enabled_restricted", combat_restricted=true },
      { api="X2Hotkey:SetOptionBindingWithIndex", status="official_enabled_restricted", combat_restricted=true },
      { api="X2Hotkey:EnableHotkey", status="official_enabled_restricted", combat_restricted=true },
      { api="X2Hotkey:SetBindingUiEvent", status="official_enabled_restricted", combat_restricted=true },
      { api="X2Hotkey:SetBindingUiEventWithIndex", status="official_enabled_restricted", combat_restricted=true },
      { api="X2Hotkey:SetOptionBindingUiEvent", status="official_enabled_restricted", combat_restricted=true },
      { api="X2Hotkey:SetOptionBindingUiEventWithIndex", status="official_enabled_restricted", combat_restricted=true },
      { api="X2House:GetCurrentHousingTaxInfo", status="official_enabled", side_effect_free=true },
      { api="X2House:GetHouseOwnerName", status="official_enabled", side_effect_free=true },
      { api="X2House:GetHouseName", status="official_enabled", side_effect_free=true },
      { api="X2House:GetHouseType", status="official_enabled", side_effect_free=true },
    },
    ["2026-08-26"] = {
      { api="X2Butler:GetChargeInfo", status="official_enabled", side_effect_free=true },
      { api="X2Store:GetRandomShopStoreRefreshCount", status="official_enabled", side_effect_free=true },
      { api="X2Input:GetMousePos", status="official_enabled", side_effect_free=true },
    },
  },

  constants = {
    X2Unit_GetUnitsInSight = {
      UO_CHARACTER=0,
      UO_NPC=1,
      UO_SLAVE=2,
      UO_HOUSING=3,
      UO_TRANSFER=4,
      UO_MATE=5,
      UO_SHIPYARD=6,
      UO_BUTLER=7,
    },
  },
}

