----------------------------------------------------------------------------------------
-- ArcheRage RU synchronized allowed-function index
-- Generated from api_functions.lua Allowed sections on 2026-08-28.
-- This is a compact reference index; restrictions/cooldowns are in api_capabilities_ru_20260828.lua.
----------------------------------------------------------------------------------------

ADDON:
ImportAPI(apiType)
ImportObject(objectType)
RegisterContentWidget(uiCategory)
RegisterContentTriggerFunc(uiCategory)
GetContent(uiCategory)
GetContentMainScriptPosVis(uiCategory)
ShowContent(uiCategory, arg)
ToggleContent(uiCategory)
GetAddonInfos()
SetAddonEnable(name, enable)
SaveAddonInfos()
FireAddon(name)
ReloadAddon(name)
ChatLog(logMessage)
GetName()
LoadData(key)
SaveData(key, table)
ClearData(key)
AddEscMenuButton(categoryId, uiContentType, iconKey, name)
UpdateEscMenuButton(uiContentType, buttonValue, colorKey)
-------
Console:
GetAttribute(attr)
ExecuteString(str)
-------
UI:
CreateWidget()
GetScreenWidth()
GetScreenHeight()
GetVirtualMemoryStats()
GetCurrentDP()
GetCurrentPolyCount()
IsDX11Supported()
IsRenderThreadSupported()
GetFrameTime()
GetFrameRate()
GetViewCameraPos()
GetViewCameraDir()
GetViewCameraAngles()
GetUIScaleRange()
GetUIScale()
SetUIScale(scale, immediatlyeApply)
SetViewCameraFov(fov)
SetViewCameraPos(pos)
SetViewCameraDir(dir)
SetViewCameraAngles(angles)
GetViewCameraFov()
IsPointVisible(point)
GetEntityByName(sEntityName)
SetUseInsertComma(use)
SetEventHandler(eventName, handler)
ReleaseEventHandler(eventName, handler)
GetUIStamp(key)
GetCurrentTimeStamp()
GetAccountUITimeStamp(key)
GetCharacterTodayPlayedTimeStamp()
GetServerTimeTable()
GetTextureKeyData(filename)
GetTextureData(filename, infoKey)
GetFontColor(key)
GetEtcValue(key)
GetUIBound(key)
SetUIBound(key, table)
ClearUIBound(key)
GetPermission(category)
InitFontSize()
GetId()
-------
X2Ability:
GetActiveAbility()
IsActiveAbility(index)
GetBuffTooltip(buffType, itemLevel)
GetAllMyActabilityInfos()
GetMyActabilityInfo(actAbilityGroupType)
-------
X2Achievement:
GetAchievementName(type)
GetCategories(kind)
GetSubcategoryInfo(subCategory)
GetCategoryCount(kind, cType, scType, filter)
GetAchievementTracingList(kind)
GetAchievementMainList(kind, sId, filter)
GetAchievementSubList(mainType filter)
GetAchievementInfo(aId)
AddTracingAchievement(aId, inLevel)
RemoveTracingAchievement(aId, inLevel)
IsTracingAchievement(aId, inLevel)
GetTodayAssignmentInfo(todayType, index)
GetTodayAssignmentInfoForChange(todayType, index)
GetTodayAssignmentCount(todayType)
GetTodayAssignmentGoal()
GetTodayAssignmentStatus()
IsTodayAssignmentQuest(todayType, questType)
GetTodayAssignmentResetCount(todayType)
-------
X2Auction:
SearchAuctionArticle(page, minLevel, maxLevel, grade, category, exactMatch, keywords, minDirectPriceStr, maxDirectPriceStr)
GetSearchedItemPage()
GetSearchedItemCount()
GetSearchedItemTotalCount()
GetSearchedItemInfo(idx)
GetLowestPrice(itemType, itemGrade)
AskMarketPrice(itemType, itemGrade, askMarketPriceUi)
-------
X2Bag:
GetBagItemInfo(bagId, slot)
EquipBagItem(slot, isAuxEquip)
CountItems()
ItemStack(slot)
MoveToEmptyBankSlot(slotIdx)
MoveToEmptyCofferSlot(slotIdx)
Capacity()
-------
X2Bank:
GetBagItemInfo(slot)
CountItems()
ItemStack(slot)
MoveToEmptyBagSlot(slotIdx)
Capacity()
-------
X2BattleField:
GetInstanceUiKindList()
GetInstanceListByKind(kind)
GetDetailInstanceInfo(instanceType)
GetInstanceName(instanceType)
-------
X2Butler:
SWAP_EQUIPMENT_MODE()
ADD_GARDEN_MODE()
RECHARGE_COST_MODE()
REGISTER_HARVEST_MODE()
CHANGE_LOOK_MODE()
REGISTER_TRACTOR_MODE()
GetChargeInfo()
-------
X2Chat:
DispatchChatMessage(filter, message)
AddRaidRecruitLinkToActiveChatInput(linkText)
-------
X2Coffer:
GetBagItemInfo(slot)
CountItems()
ItemStack(slot)
MoveToEmptyBagSlot(slot)
Capacity()
-------
X2CombatResource:
GetCombatResourceInfo()
GetCombatResourceInfoByGroupType(groupType)
CheckCombatResourceMaxPointByGroupType(groupType)
-------
X2Craft:
GetCraftBaseInfo(craftType)
GetCraftMaterialInfo(craftType, doodadId)
GetCraftProductInfo(craftType)
GetCraftTypeByItemType(itemType)
-------
X2EquipSlotReinforce:
GetMaterialInfo(equipSlotIndex, level)
GetReinforceInfo(equipSlotIndex)
GetAttributeType(equipSlotIndex)
IsFullExp(equipSlotIndex)
GetSetEffects(attributeType)
GetSetEffectTopLevel(attributeType)
GetAttributeTotalLevel(attributeType)
GetNextSetApplyLevel(attributeType)
GetLevelEffectChangeUIInfo(equipSlotIndex)
GetLevelEffectStep(equipSlotIndex)
GetLevelEffectInfoByEquipSlot(equipSlotIndex)
HasNextSetEffect(attributeType)
IsInGameShopItemTag(itemType)
SuitableLevelForEquipSlotReinforce()
GetAppliedAllLevelEffect()
GetAppliedAllSetEffect()
GetAppliedAllBundleEffect()
GetTotalReinforceLevel()
GetBundleEffectTopLevel()
GetBundleEffectInfos()
-------
X2Equipment:
MateUnequipItem(unit, equipSlot)
PickupMateEquippedItem(unit, equipSlot)
GetEquippedItemTooltipInfo(equipSlot, targetEquippedItem)
GetEquippedItemType(equipSlot)
-------
X2Faction:
IsMyExpeditionMember(charName)
-------
X2Family:
GetMemberList(allMember)
-------
X2Friend:
IsMyFriend(charName)
GetFriendList(allMember)
GetBlockList()
BlockUser(charName)
UnblockUser(charName)
GetMuteList()
MuteUser(charName)
UnmuteUser(charName)
-------
X2GuildBank:
GetBagItemInfo(slot)
CountItems()
ItemStack(slot)
-------
X2Hotkey:
SaveHotKey()
BindingToOption()
OptionToBinding()
GetOptionBinding(action, index, option, arg)
GetOptionBindingButton(buttonName, index)
SetOptionBindingButtonWithIndex(buttonName, key)
SetOptionBindingWithIndex(action, key, index, arg)
RemoveOptionBinding(action, index, arg)
EnableHotkey(enable)
IsValidActionName(action)
IsOverridableAction(action)
GetBindingUiEvent(actionName, index)
SetBindingUiEvent(actionName, key)
SetBindingUiEventWithIndex(actionName, key, index)
GetOptionBindingUiEvent(actionName, index)
SetOptionBindingUiEvent(actionName, key)
SetOptionBindingUiEventWithIndex(actionName, key)
-------
X2Input:
IsShiftKeyDown()
IsControlKeyDown()
IsAltKeyDown()
GetMousePos()
-------
X2Item:
InfoFromLink(linkText)
IIK_TYPE()
IIK_NAME()
IIK_GRADE()
IIK_GRADE_STR()
IIK_IMPL()
IIK_SELL()
IIK_STACK()
IIK_CATEGORY()
IIK_CONSUME_ITEM()
IIK_SOCKET_MODIFIER()
NORMAL_ITEM_GRADE()
POOR_ITEM_GRADE()
MAX_SET_ITEMS()
-------
X2Locale:
HasLocalizeUiText()
LocalizeUiText()
LocalizeFormatUiText()
TextFormating(text)
GetLocale()
GetLocaleIndex()
GetKeyboardLayout()
LocalizeNonUiText()
-------
X2Map:
GetZoneStateInfoByZoneId(zoneId)
ShowWorldmapLocation(zoneGroupId, x, y, z)
-------
X2Option:
Save()
Reset()
CreateOptionItemFloat(name, value)
CreateOptionItemString(name, value)
GetOptionItemValue(optionType)
GetOptionItemValueByName(name)
SetItemFloatValue(optionType, value)
SetItemFloatValueWithoutModify(optionType, value)
SetItemFloatValueByName(name, value)
SetItemStringValue(optionType, value)
SetItemStringValueByName(name, value)
SetItemDefaultFloatValue(optionType, value)
SetItemDefaultFloatValueByName(name, value)
SetItemDefaultStringValue(optionType, value)
SetItemDefaultStringValueByName(name, value)
GetResolutionCount()
GetResolution(index)
GetCursorSize()
GetBasicCursorShape()
EnumAAFormats()
GetNextSysSpecFullValue()
GetMinxMaxOfMouseSensitivity()
IsPixelSyncSupported()
HasOceanSimulateOption()
OptimizationEnable(enable)
GetSubOptionItemList(modeOptionId, selected)
GetOptionInfo(optionItemType)
GetHotkeyInfo(hotkeyActionType)
GetConsoleVariable(name)
SetConsoleVariable(name, value)
-------
X2Player:
GetUnitAppellationRouteList()
GetAppellationCount()
GetAppellations(routeFilter, keyword, pageIndex)
GetAppellationsCount(routeFilter, keyword)
ChangeAppellation(nameType, effectType)
GetShowingAppellation()
GetEffectAppellation()
GetAppellationMyLevelInfo()
GetAppellationBuffInfoByLevels()
GetAppellationRouteInfo(type)
GetAppellationStampInfos()
GetAppellationStampInfo(stampId)
GetAppellationMyStamp()
GetAppellationChangeItemInfo()
GetStampChangeItemInfo()
PlayerInCombat()
-------
X2Quest:
GetQuestContextMainTitle(type)
SetTrackingActiveQuest(idx)
GetActiveQuestListCount()
GetActiveQuestType(idx)
IsCompleted(type)
IsReadyForCompleteQuest(questType)
-------
X2Resident:
RefreshResidentMembers(zoneGroupType, bool, int)
GetResidentMembers(zoneGroupType, bool, int)
RequestHousingTradeList(zoneGroupType, filterindex, searchWord)
FilterHousingTradeList(filterindex, searchWord)
GetResidentBoardContent(boardType)
-------
X2SiegeWeapon:
GetSiegeWeaponSpeed()
GetSiegeWeaponTurnSpeed()
-------
X2Skill:
GetSkillTooltip(skillId, itemType)
Info(skillId)
GetCooldown(skillId, ignoreGlobalCooldown)
GetMateCooldown(skillId, ignoreGlobalCooldown, mateType)
-------
X2Sound:
PlayUISound(soundPackItemName)
IsPlaying(soundId)
StopSound(soundId)
PlayMusic(soundPackItemName)
StopMusic()
-------
X2Squad:
CreateSquad(selectedField, openType, explanation, partyInvitation, limitLevel, limitGearScore)
-------
X2Store:
GetSpecialtyRatio()
GetZoneSpecialtyRatio()
GetSpecialtyRatioBetween(fromZoneGroup, toZoneGroup)
GetProductionZoneGroups()
GetSellableZoneGroups(fromZoneGroup)
GetRandomShopStoreRefreshCount()
-------
X2Team:
GetRole(teamIndex, memberIndex)
SetRole(role)
MoveTeamMember(frommemberIndex, tomemberIndex)
MoveTeamMemberToParty(frommemberIndex, toParty)
KickTeamMember(memberIndex, teamRoleType)
KickTeamMemberByName(charName, teamRoleType)
GetTeamRoleType()
RaidRecruitAdd(type, subType, headcount, limitLevel, autoJoin, msg, hour, minute, limitGearPoint)
RaidRecruitDel()
GetLinkText()
RaidApplicantList()
RaidApplicantAccept(charIds)
RaidApplicantReject(charIds)
MakeTeamOwner(unit)
InviteToTeam(charName, isParty)
-------
X2Time:
GetGameTime()
GetServerTime()
-------
X2Unit:
GetUnitId(unit)
UnitName(unit)
UnitNameWithWorld(unit)
UnitHealth(unit)
UnitMaxHealth(unit)
UnitHealthInfo(unit)
UnitMana(unit)
UnitMaxMana(unit)
UnitManaInfo(unit)
UnitLevel(unit)
UnitCastingInfo(unit)
UnitDistance(unit)
UnitGearScore(unit, comma)
UnitBuffTooltip(unit, buffIndex)
UnitBuff(unit, buffIndex)
UnitBuffCount(unit)
UnitDeBuff(unit, buffIndex)
UnitDeBuffCount(unit)
UnitDeBuffTooltip(unit, buffIndex)
UnitHiddenBuff(unit, buffIndex)
UnitHiddenBuffCount(unit)
UnitHiddenBuffTooltip(unit, buffIndex)
UnitRemovableDebuffTooltip(unit, buffIndex)
UnitRemovableDebuff(unit, buffIndex)
UnitRemovableDebuffCount(unit)
GetUnitWorldPositionByTarget(unit, isLocal)
GetUnitScreenPosition(unit)
GetTargetAbilityTemplates(target)
GetTargetUnitId()
GetUnitNameById(stringId)
GetUnitInfoById(stringId)
GetCurrentZoneGroup()
SetOverHeadMarker(unit, markerIndex)
RemoveAllOverHeadMarker()
GetOverHeadMarker(unit)
GetOverHeadMarkerUnitId(markerIndex)
UnitInfo(unit)
UnitModifierInfo(unit)
GetUnitsInSight(unitOwner)
-------
X2Util:
XLGAMES()
TENCENT()
GAMEON()
KAKAONA()
MAILRU()
PLAYWITH()
XLGAMES_TH()
-------
X2World:
GetCurrentWorldName()
-------
