local pass,fail=0,0
local function Test(name,fn)
  local ok,err=pcall(fn)
  if ok then pass=pass+1;print('PASS income '..name) else fail=fail+1;print('FAIL income '..name..': '..tostring(err)) end
end
local function Boot(opts)
  opts=opts or {}
  local H=dofile('tools/rs_udf_numeric_test_host.lua');local S,P,io=H.Boot(opts.disk);S.__incomeTestDisk=io.disk
  local clock={date={year=2026,month=9,day=13},tasks={},callbacks={}}
  X2Unit={UnitNameWithWorld=function()return 'Income@TestWorld' end,GetUnitId=function(_,unit)return unit=='player' and 'player-unit-id' or nil end}
  -- Maintenance: the bundled API reference marks X2Bag:GetCurrency as not allowed.
  -- Keep a tripwire in the test host so any future regression that probes it fails loudly.
  local currencyCalls=0
  X2Bag={GetCurrency=function() currencyCalls=currencyCalls+1;error('forbidden_getcurrency_called') end}
  S.__incomeGetCurrencyCalls=function()return currencyCalls end
  S.Utils.GetServerTime=function()return clock.date end
  S.Scheduler={AddTask=function(_,key,ms,fn)clock.tasks[key]=fn;return true end,RemoveTask=function(_,key)clock.tasks[key]=nil;return true end}
  local nativeUnavailable=opts.nativeUnavailable or {}
  S.Events={SubscribeOptional=function(_,event,owner,cb)
      if nativeUnavailable[event]==true then return false end
      clock.callbacks[event]={owner=owner,cb=cb};return true
    end,
    UnsubscribeOwner=function(_,owner)for event,row in pairs(clock.callbacks)do if row.owner==owner then clock.callbacks[event]=nil end end;return true end}
  CMF_SELF_MONEY_CHANGED=40;CMF_SELF_HONOR_POINT_CHANGED=41;CMF_SELF_LIVING_POINT_CHANGED=42
  dofile('features/life/rs_daily_ledger.lua')
  dofile('features/life/rs_daily_income_source.lua')
  local L=assert(S.Features.DailyLedger);local A=assert(S.Features.DailyIncomeSource)
  assert(L:Enable())
  return S,L,A,clock
end
Test('adapter remains provisional until an explicit structured delta is observed',function()
  local _,L,A=Boot();local p=L:GetProjection();assert(p.verifiedSources==0)
  local ok,why=A:HandleChatMessage(0,0,'','unparsed text',{filterType=CMF_SELF_MONEY_CHANGED,isUserChat=false})
  assert(ok==false and why=='no_explicit_delta')
  p=L:GetProjection();assert(p.verifiedSources==0 and p.rows[1].value==nil)
end)
Test('native direct-delta authority prevents chat delta double counting when native event is available',function()
  local _,L,A=Boot();local ok,why=A:HandleChatMessage(0,0,'','',{filterType=CMF_SELF_MONEY_CHANGED,isUserChat=false,moneyDelta=12500})
  assert(ok==false and tostring(why):find('source_locked:native:player_money',1,true))
  local p=L:GetProjection();assert(p.verifiedSources==0 and p.rows[1].status=='probing' and p.rows[1].value==nil)
end)
Test('exact structured chat delta remains a fallback when the matching native event is unavailable',function()
  local _,L,A=Boot({nativeUnavailable={PLAYER_MONEY=true}})
  assert(A:HandleChatMessage(0,0,'','',{filterType=CMF_SELF_MONEY_CHANGED,isUserChat=false,moneyDelta=12500}))
  local p=L:GetProjection();assert(p.verifiedSources==1 and p.rows[1].value==12500 and p.rows[1].status=='ready')
end)
Test('honor and living structured deltas are fallback-only per unavailable native channel',function()
  local _,L,A=Boot({nativeUnavailable={PLAYER_HONOR_POINT=true,PLAYER_LIVING_POINT=true}})
  assert(A:HandleChatMessage(0,0,'','',{filterType=CMF_SELF_HONOR_POINT_CHANGED,isUserChat=false,honorDelta=37}))
  assert(A:HandleChatMessage(0,0,'','',{filterType=CMF_SELF_LIVING_POINT_CHANGED,isUserChat=false,livingDelta=-8}))
  local p=L:GetProjection();assert(p.verifiedSources==2);assert(p.rows[2].value==37);assert(p.rows[4].value==-8)
end)
Test('generic amount and unrelated numeric metadata never become income',function()
  local _,L,A=Boot();assert(not A:HandleChatMessage(0,0,'','',{filterType=CMF_SELF_MONEY_CHANGED,isUserChat=false,amount=999,sequence=7}))
  assert(not A:HandleChatMessage(0,0,'','',{filterType=999,isUserChat=false,moneyDelta=500}))
  local p=L:GetProjection();assert(p.verifiedSources==0);for _,r in ipairs(p.rows)do assert(r.value==nil)end
end)
Test('user chat is ignored even if metadata is forged',function()
  local _,L,A=Boot();assert(not A:HandleChatMessage(0,0,'Player','',{filterType=CMF_SELF_HONOR_POINT_CHANGED,isUserChat=true,honorDelta=500}))
  assert(L:GetProjection().verifiedSources==0)
end)
Test('experience source is provisionally registered when EXP_CHANGED is available',function()
  local _,L,A,c=Boot();local p=L:GetProjection()
  assert(c.callbacks.EXP_CHANGED~=nil)
  assert(p.rows[3].key=='experience' and p.rows[3].status=='probing' and p.rows[3].value==nil)
end)
Test('EXP_CHANGED counts only the player exact delta string and updates immediately',function()
  local _,L,A,c=Boot();local row=assert(c.callbacks.EXP_CHANGED)
  row.cb(row.owner,'player-unit-id',1200,'1200')
  local p=L:GetProjection();assert(p.verifiedSources==1 and p.rows[3].value==1200 and p.rows[3].status=='ready')
  row.cb(row.owner,'player-unit-id',350,'350')
  p=L:GetProjection();assert(p.rows[3].value==1550)
  local h=A:GetHealth();assert(h.nativeEventCounts.EXP_CHANGED==2 and h.nativeLastAccepted.experience==350)
end)
Test('EXP_CHANGED rejects other units and malformed payloads',function()
  local _,L,A,c=Boot();local row=assert(c.callbacks.EXP_CHANGED)
  row.cb(row.owner,'other-unit-id',900,'900')
  row.cb(row.owner,'player-unit-id',0,'0')
  row.cb(row.owner,'player-unit-id',nil,'not-a-number')
  local p=L:GetProjection();assert(p.rows[3].value==nil and p.verifiedSources==0)
  local h=A:GetHealth();assert(h.nativeInvalidDeltas.experience>=2)
end)
Test('pause releases all income listeners but retains already observed total',function()
  local _,L,A,c=Boot();assert(c.callbacks.CHAT_MESSAGE and c.callbacks.PLAYER_MONEY and c.callbacks.PLAYER_HONOR_POINT and c.callbacks.PLAYER_LIVING_POINT)
  -- PLAYER_MONEY is a direct change event, so one +100 receipt must be retained verbatim.
  local money=assert(c.callbacks.PLAYER_MONEY);money.cb(money.owner,100,'100',0)
  assert(L:GetProjection().rows[1].value==100)
  assert(L:SetPaused(true,'test'));assert(next(c.callbacks)==nil)
  local p=L:GetProjection();assert(p.rows[1].value==100 and p.rows[1].status=='paused')
end)
Test('diagnostics are bounded and do not retain full chat text',function()
  local _,_,A=Boot();for i=1,20 do A:HandleChatMessage(0,0,'','secret '..i,{isUserChat=false,foo=i}) end
  local h=A:GetHealth();assert(h.samples<=8 and h.lastMessage==nil and type(h.lastShape)=='string' and type(h.lastMeta)=='string');assert(not string.find(h.lastMeta,'secret',1,true))
end)
Test('channel CMF explicit delta fallback works only when matching native event is unavailable',function()
  local _,L,A=Boot({nativeUnavailable={PLAYER_MONEY=true}});assert(A:HandleChatMessage(CMF_SELF_MONEY_CHANGED,0,'','',{isUserChat=false,moneyDelta=321}))
  local p=L:GetProjection();assert(p.verifiedSources==1);assert(p.rows[1].value==321)
  local h=A:GetHealth();assert(h.lastCategorySource=='channel')
end)
Test('unstructured RU envelope is recorded before fail closed rejection',function()
  local _,L,A=Boot();local ok,why=A:HandleChatMessage(CMF_SELF_HONOR_POINT_CHANGED,0,'','Honor changed',nil)
  assert(ok==false and why=='no_explicit_delta')
  assert(L:GetProjection().verifiedSources==0)
  local h=A:GetHealth();assert(h.totalEnvelopes>=1 and h.lastEnvelope:find('channel=41',1,true));assert(h.lastEnvelope:find('infoType=nil',1,true))
end)
Test('native resource events use direct deltas and invalid empty payload stays unverified',function()
  local _,L,A,c=Boot();assert(c.callbacks.PLAYER_MONEY and c.callbacks.PLAYER_HONOR_POINT and c.callbacks.PLAYER_LIVING_POINT)
  c.callbacks.PLAYER_MONEY.cb(c.callbacks.PLAYER_MONEY.owner,12345,'12345',0)
  c.callbacks.PLAYER_HONOR_POINT.cb(c.callbacks.PLAYER_HONOR_POINT.owner,77,'77',false)
  c.callbacks.PLAYER_LIVING_POINT.cb(c.callbacks.PLAYER_LIVING_POINT.owner)
  local h=A:GetHealth();assert(h.nativeEventCounts.PLAYER_MONEY==1 and h.nativeEventCounts.PLAYER_HONOR_POINT==1 and h.nativeEventCounts.PLAYER_LIVING_POINT==1)
  assert(h.nativeEventLast.PLAYER_MONEY:find('1:number=12345',1,true));assert(h.nativeInvalidDeltas.living==1)
  local p=L:GetProjection();assert(p.verifiedSources==2 and p.rows[1].value==12345 and p.rows[2].value==77 and p.rows[4].value==nil)
end)
Test('event bus owner prefix keeps CHAT_MESSAGE fallback arguments aligned',function()
  local _,L,A,c=Boot({nativeUnavailable={PLAYER_MONEY=true}});local row=assert(c.callbacks.CHAT_MESSAGE)
  assert(row.cb(row.owner,0,0,'','',{filterType=CMF_SELF_MONEY_CHANGED,isUserChat=false,moneyDelta=777}))
  local p=L:GetProjection();assert(p.verifiedSources==1 and p.rows[1].value==777)
end)
Test('event bus owner prefix is excluded from native direct-delta payload',function()
  local _,L,A,c=Boot();local row=assert(c.callbacks.PLAYER_MONEY)
  row.cb(row.owner,12345,'12345',0)
  local h=A:GetHealth();assert(h.nativeEventCounts.PLAYER_MONEY==1)
  assert(h.nativeEventLast.PLAYER_MONEY:find('1:number=12345',1,true))
  assert(not h.nativeEventLast.PLAYER_MONEY:find('1:table',1,true))
  assert(L:GetProjection().verifiedSources==1 and L:GetProjection().rows[1].value==12345)
end)
Test('pause and resume skip paused events without inventing a balance gap',function()
  local _,L,A,c=Boot();local row=assert(c.callbacks.PLAYER_MONEY)
  row.cb(row.owner,100,'100',0);assert(L:GetProjection().rows[1].value==100)
  assert(L:SetPaused(true,'test'));assert(c.callbacks.PLAYER_MONEY==nil)
  assert(L:SetPaused(false,'test'));row=assert(c.callbacks.PLAYER_MONEY)
  row.cb(row.owner,50,'50',0);assert(L:GetProjection().rows[1].value==150)
end)
Test('forbidden X2Bag GetCurrency is never called',function()
  local S,L,A,c=Boot();assert(S.__incomeGetCurrencyCalls()==0)
  local row=assert(c.callbacks.PLAYER_MONEY);row.cb(row.owner,20348,'20348',0)
  assert(S.__incomeGetCurrencyCalls()==0 and L:GetProjection().rows[1].value==20348)
end)
Test('direct delta totals survive same-day reload without any balance baseline',function()
  local S,L,A,c=Boot();local row=assert(c.callbacks.PLAYER_MONEY)
  row.cb(row.owner,100,'100',0)
  local P=S.Persistence;assert(P:Flush(L.StoreId));local disk=S.__incomeTestDisk;assert(disk~=nil)
  local _,L2,A2,c2=Boot({disk=disk});local row2=assert(c2.callbacks.PLAYER_MONEY)
  row2.cb(row2.owner,50,'50',0)
  local r=L2:GetProjection().rows[1];assert(r.value==150 and r.status=='ready')
end)

Test('PLAYER_MONEY is a direct delta event and first gain is counted immediately',function()
  local _,L,A,c=Boot();local row=assert(c.callbacks.PLAYER_MONEY)
  row.cb(row.owner,40834,'40834',0)
  local p=L:GetProjection();assert(p.verifiedSources==1 and p.rows[1].value==40834 and p.rows[1].status=='ready')
  row.cb(row.owner,125,'125',0)
  p=L:GetProjection();assert(p.rows[1].value==40959)
end)
Test('PLAYER_MONEY uses signed changeStr magnitude in copper units',function()
  local _,L,A,c=Boot();local row=assert(c.callbacks.PLAYER_MONEY)
  row.cb(row.owner,-200,'-200',0)
  local p=L:GetProjection();assert(p.rows[1].value==-200)
end)
Test('PLAYER_HONOR_POINT and PLAYER_LIVING_POINT are direct deltas',function()
  local _,L,A,c=Boot()
  local honor=assert(c.callbacks.PLAYER_HONOR_POINT);local living=assert(c.callbacks.PLAYER_LIVING_POINT)
  honor.cb(honor.owner,4155,'4155',false)
  living.cb(living.owner,-37,'-37')
  local p=L:GetProjection();assert(p.rows[2].value==4155 and p.rows[4].value==-37)
end)
Test('first direct delta clears legacy balance-mode totals before counting',function()
  local _,L,A,c=Boot();local ch=L.State.channels.gold
  ch.net=999;ch.gain=999;ch.spent=0;ch.samples=3;ch.balance=20348
  local row=assert(c.callbacks.PLAYER_MONEY);row.cb(row.owner,500,'500',0)
  local p=L:GetProjection();assert(p.rows[1].value==500)
  assert(ch.balance==nil and ch.gain==500 and ch.samples==1)
end)

print('INCOME RESULT '..pass..' passed / '..fail..' failed');if fail>0 then error('income tests failed')end
