-- Phase 0 recovered regression coverage for explicit failed-store evidence export.
return function(ctx)
    local S,Test,Copy,Equal=ctx.S,ctx.Test,ctx.Copy,ctx.Equal;local P,store,disk=S.Persistence,ctx.store,ctx.disk
    local fields={'writeFenced','writeFenceReason','lastError','needsBarrierVerify','lastVerifyOk','lastBarrierVerifyOk','consecutiveSaveFailures'}
    local function Snap()local t={};for _,k in ipairs(fields)do t[k]=store[k]end;return t end
    local function Restore(t)for _,k in ipairs(fields)do store[k]=t[k]end end
    local function WithFailure(run)local saved=Snap();local ok,err=pcall(function()assert(P:SaveStore(store.id,{force=true,verifyAfterSave=true}));store.lastError='phase0_synthetic_readback_failure';store.needsBarrierVerify=true;store.lastVerifyOk=false;run(assert(P:ResolveStoreKey(store)))end);Restore(saved);assert(ok,err)end
    Test('healthy Store cannot export raw evidence or trigger a Native read',function()local saved=Snap();store.writeFenced=false;store.lastError=nil;store.needsBarrierVerify=false;store.lastVerifyOk=nil;store.consecutiveSaveFailures=0;local original=S.Api.LoadData;local reads=0;S.Api.LoadData=function(...)reads=reads+1;return original(...)end;local value,err=P:BuildFailedStoreEvidenceText(store.id);S.Api.LoadData=original;Restore(saved);assert(value==nil and err=='store_not_fenced' and reads==0)end)
    Test('current durable failure exports one detached read-only evidence frame',function()WithFailure(function(key)local before=Copy(disk[key]);local original=S.Api.LoadData;local reads=0;S.Api.LoadData=function(...)reads=reads+1;return original(...)end;local text,err=P:BuildFailedStoreEvidenceText(store.id);S.Api.LoadData=original;assert(text,err);assert(reads==1);assert(text:find('RS%-PERSIST%-EVIDENCE%-1') and text:find('RS%-PERSIST%-EVIDENCE%-END'));assert(Equal(before,disk[key]))end)end)
    Test('compact evidence keeps raw payload while removing redundant wrapper fields',function()WithFailure(function()local full=assert(P:BuildFailedStoreEvidenceText(store.id));local compact=assert(P:BuildFailedStoreEvidenceText(store.id,{compact=true}));assert(#compact<#full)end)end)
    Test('Native read exception is contained and failure state is preserved',function()WithFailure(function()local original=S.Api.LoadData;S.Api.LoadData=function()error('phase0_read_exception')end;local text,err=P:BuildFailedStoreEvidenceText(store.id);S.Api.LoadData=original;assert(text==nil and tostring(err):find('evidence_load_exception:',1,true));assert(P:GetStoreFailureKind(store)~=nil)end)end)
    Test('cyclic Native payload is rejected whole instead of partially serialized',function()WithFailure(function()local original=S.Api.LoadData;S.Api.LoadData=function()local raw={};raw.self=raw;return raw end;local text,err=P:BuildFailedStoreEvidenceText(store.id);S.Api.LoadData=original;assert(text==nil and tostring(err):find('evidence_payload:',1,true))end)end)
end
