local passed,failed=0,0
local function T(name,fn)local ok,err=pcall(fn);if ok then passed=passed+1;print('PASS scope '..name)else failed=failed+1;print('FAIL scope '..name..': '..tostring(err))end end
local Boot=dofile('tools/rs_pvp_hud_test_host.lua')
T('schema8 nested defaults and schema7 migration duplicates both scopes',function()
 local h,S,F=Boot({noRenderer=true});local st=assert(S.Persistence:GetStore('v3.buff_display'))
 assert(F.SchemaVersion==8,'schema')
 local d=st.default();assert(d.settings.tracked.player and d.settings.tracked.target,'nested')
 local legacy=d;legacy.settings.tracked={buff={21},debuff={82},auto={123}}
 local up=st.migrate(legacy,7,8)
 for _,scope in ipairs({'player','target'})do assert(up.settings.tracked[scope].buff[1]==21 and up.settings.tracked[scope].debuff[1]==82 and up.settings.tracked[scope].auto[1]==123,scope)end
end)
T('independent scope channels render only requested HUD',function()
 local h,S,F=Boot({noRenderer=true});local settings=F:GetDefaultSettingsSnapshot()
 assert(F:SetTrackedChannel(21,'target','buff',true))
 local idx=F:BuildTrackedIndex(F.State.settings)
 assert(idx.target.buff[21] and not idx.player.buff[21])
 local row={id=21,name='x',category='buff',detectionSource='normal'}
 local ph=F.ProjectPlates({buffRows={row},debuffRows={}},F:GetScopeLayoutSettings('player'),idx,'player')
 local th=F.ProjectPlates({buffRows={row},debuffRows={}},F:GetScopeLayoutSettings('target'),idx,'target')
 assert(#ph.buffs==0 and #th.buffs==1)
 local statusMap={[21]={name='x',sources={buff=true},stack=1}}
 local pr=F.ProjectStatusMap(statusMap,{},F.State.settings,'player',10,idx)
 local tr=F.ProjectStatusMap(statusMap,{},F.State.settings,'target',10,idx)
 assert(pr[1] and pr[1].tracked==false,'player live projection inherited target-only tracking')
 assert(tr[1] and tr[1].tracked==true,'target live projection lost target tracking')
end)
T('four explicit channels are independent and first manual placement retires hidden Auto ownership',function()
 local h,S,F=Boot({noRenderer=true})
 assert(F:SetTrackedChannel(21,'player','auto',true))
 assert(F:SetTrackedChannel(21,'target','auto',true))
 assert(F:SetTrackedChannel(21,'player','buff',true))
 assert(not F:IsTrackedChannel(21,'player','auto'),'same-scope Auto survived manual placement')
 assert(not F:IsTrackedChannel(21,'target','auto'),'other-scope hidden Auto would prevent target-only/self-only control')
 assert(F:SetTrackedChannel(21,'player','debuff',true))
 assert(F:IsTrackedChannel(21,'player','buff') and F:IsTrackedChannel(21,'player','debuff'))
 assert(F:SetTrackedChannel(21,'target','buff',true))
 assert(F:IsTrackedChannel(21,'target','buff'))
 assert(F:SetTrackedChannel(21,'player','buff',false))
 assert(not F:IsTrackedChannel(21,'player','buff') and F:IsTrackedChannel(21,'player','debuff') and F:IsTrackedChannel(21,'target','buff'))
end)
T('management tracked view aggregates scope labels and filters channels',function()
 local h,S,F=Boot({noRenderer=true});if type(F.GetManagementProjection)~='function' then for _,file in ipairs({'data/rs_skill_effects.lua','data/rs_combat_ability_catalog.lua','data/ids/rs_buff_ids.lua','data/rs_status_tracking_catalog.lua'}) do dofile(file) end;dofile('features/combat/buff_display/rs_buff_display_management.lua') end
 assert(F:SetTrackedChannel(21,'player','buff',true))
 assert(F:SetTrackedChannel(21,'target','buff',true))
 local rows=F:GetManagementProjection({view='tracked',filter='all'})
 local row;for _,v in ipairs(rows) do if v.id==21 then row=v break end end
 assert(row and row.trackedText=='自身·Buff / 目标·Buff',row and row.trackedText or 'missing')
 assert(#F:GetManagementProjection({view='tracked',filter='player'})==1,'player filter')
 assert(#F:GetManagementProjection({view='tracked',filter='target'})==1,'target filter')
 assert(#F:GetManagementProjection({view='tracked',filter='tracked_buff'})==1,'buff filter')
 assert(#F:GetManagementProjection({view='tracked',filter='tracked_debuff'})==0,'debuff filter')
end)
T('builtin pack imports effects to both scopes in one scoped tracking model',function()
 local h,S,F=Boot({noRenderer=true});if type(F.ImportBuiltinPack)~='function' then for _,file in ipairs({'data/rs_skill_effects.lua','data/rs_combat_ability_catalog.lua','data/ids/rs_buff_ids.lua','data/rs_status_tracking_catalog.lua'}) do dofile(file) end;dofile('features/combat/buff_display/rs_buff_display_management.lua') end
 local ok,msg,result=F:ImportBuiltinPack('recommended',false);assert(ok,msg)
 local settings=F.State.settings
 assert(#settings.tracked.player.buff+#settings.tracked.player.debuff+#settings.tracked.player.auto>0,'player empty')
 assert(#settings.tracked.target.buff+#settings.tracked.target.debuff+#settings.tracked.target.auto>0,'target empty')
 assert(#settings.tracked.player.buff==#settings.tracked.target.buff,'buff mismatch')
 assert(#settings.tracked.player.debuff==#settings.tracked.target.debuff,'debuff mismatch')
 assert(#settings.tracked.player.auto==#settings.tracked.target.auto,'auto mismatch')
end)
T('transfer v3 round trip preserves six scoped channels including dual classification',function()
 local h,S,F=Boot({noRenderer=true});for _,file in ipairs({'data/rs_skill_effects.lua','data/rs_combat_ability_catalog.lua','data/ids/rs_buff_ids.lua','data/rs_status_tracking_catalog.lua'}) do dofile(file) end;dofile('features/combat/buff_display/rs_buff_display_transfer_v2.lua')
 assert(F:SetTrackedChannel(21,'player','buff',true));assert(F:SetTrackedChannel(21,'player','debuff',true));assert(F:SetTrackedChannel(82,'target','debuff',true))
 local text=F:SerializeExport(F:ExportAll('tracking'))
 assert(text:find('FORMAT=replicatedsuite.buff_display.v3',1,true),'v3 format missing')
 assert(text:find('PLAYER_BUFF=21',1,true) and text:find('PLAYER_DEBUFF=21',1,true),'player channels missing')
 assert(text:find('TARGET_DEBUFF=82',1,true),'target channel missing')
 local parsed=F:ParseImportText(text);assert(#parsed.errors==0,parsed.errors[1]);local t=parsed.data.tracked
 assert(t.player.buff[1]==21 and t.player.debuff[1]==21 and t.target.debuff[1]==82,'round trip lost scoped channels')
end)
T('legacy global transfer lists migrate to both scopes',function()
 local h,S,F=Boot({noRenderer=true});for _,file in ipairs({'data/rs_skill_effects.lua','data/rs_combat_ability_catalog.lua','data/ids/rs_buff_ids.lua','data/rs_status_tracking_catalog.lua'}) do dofile(file) end;dofile('features/combat/buff_display/rs_buff_display_transfer_v2.lua')
 local parsed=F:ParseImportText('FORMAT=replicatedsuite.buff_display.v2\nSTORE_SCHEMA=7\nBUFF=21\nDEBUFF=82\nAUTO=123')
 assert(#parsed.errors==0,parsed.errors[1]);for _,scope in ipairs({'player','target'})do local t=parsed.data.tracked[scope];assert(t.buff[1]==21 and t.debuff[1]==82 and t.auto[1]==123,scope)end
end)
T('quick import scope target overwrite does not alter player channels',function()
 local h,S,F=Boot({noRenderer=true});for _,file in ipairs({'data/rs_skill_effects.lua','data/rs_combat_ability_catalog.lua','data/ids/rs_buff_ids.lua','data/rs_status_tracking_catalog.lua'}) do dofile(file) end;dofile('features/combat/buff_display/rs_buff_display_transfer_v2.lua')
 assert(F:SetTrackedChannel(99,'player','buff',true));assert(F:SetTrackedChannel(88,'target','buff',true))
 local ok,err=F:ImportTrackedIds('21','buff','overwrite','target');assert(ok,err)
 assert(F:IsTrackedChannel(99,'player','buff'),'player changed by target overwrite')
 assert(F:IsTrackedChannel(21,'target','buff') and not F:IsTrackedChannel(88,'target','buff'),'target overwrite incorrect')
end)
if failed>0 then error(('TRACKING_SCOPE_RESULT passed=%d failed=%d'):format(passed,failed))end
print(('TRACKING_SCOPE_RESULT passed=%d failed=%d'):format(passed,failed))
