"""Unified report transport regression; generated by the real Lua Store audit.

No user Lua is executed. The outer byte count detects copy truncation, while
individual raw-store sections retain the existing strict evidence checksum.
This is not proof that the ArcheRage client's clipboard or UI has been tested.
"""
from pathlib import Path
import re
import unittest

from rs_persistence_evidence_decode import decode_evidence
from rs_report_copy_decode import unwrap_report

ROOT = Path(__file__).resolve().parent


def read_blocks(text: str) -> dict:
    text = unwrap_report(text)
    if len(text.encode('utf-8')) > 1048576:
        raise ValueError('Report exceeds its byte budget')
    header = re.match(r'RS-SELF-CHECK-1\nID=([0-9.]+)\n', text)
    footer = re.search(r'^\[RESULT\] [^\n]*\nBODY_BYTES=(\d+)\nRS-SELF-CHECK-END ID=([0-9.]+)\s*\Z', text, re.M)
    if not header or not footer or header[1] != footer[2]:
        raise ValueError('Missing/mismatched report markers')
    if len(text[:footer.start()].encode('utf-8')) != int(footer[1]):
        raise ValueError('Report body byte length mismatch')
    blocks = {}
    pattern = r'^\[RAW_STORE ([^\]\n]+)\]\n(RS-PERSIST-EVIDENCE-1\n.*?\nRS-PERSIST-EVIDENCE-END)\n\[/RAW_STORE \1\]'
    for match in re.finditer(pattern, text, re.M | re.S):
        name, payload = match.groups()
        if name in blocks:
            raise ValueError('Duplicate Store section')
        decoded = decode_evidence(payload)
        stored_name = next(row['value']['text'] for row in decoded['entries'] if row['key'].get('text') == 'store')
        if name != stored_name:
            raise ValueError('Store section identity mismatch')
        blocks[name] = decoded
    return blocks


class UnifiedReportTests(unittest.TestCase):
    def sample(self):
        return (ROOT / '.self_check_real_evidence.txt').read_text(encoding='utf-8')

    def test_single_copy_contains_three_complete_real_codec_evidence_blocks(self):
        blocks = read_blocks(self.sample())
        self.assertEqual(set(blocks), {'v3.buff_display', 'v3.death_review', 'v3.life.trade'})
        for node in blocks.values():
            raw = next(row['value'] for row in node['entries'] if row['key'].get('text') == 'raw')
            self.assertEqual(raw['type'], 'table')

    def test_windows_newlines_and_bom_do_not_require_manual_cleanup(self):
        text = self.sample()
        self.assertEqual(read_blocks('\ufeff' + text.replace('\n', '\r\n')), read_blocks(text))

    def test_truncated_copy_is_rejected(self):
        with self.assertRaises(ValueError):
            read_blocks(self.sample()[:-30])

    def test_different_report_end_id_is_rejected(self):
        with self.assertRaises(ValueError):
            read_blocks(self.sample().replace('RS-SELF-CHECK-END ID=1.1', 'RS-SELF-CHECK-END ID=9.9'))

    def test_missing_bytes_are_rejected(self):
        with self.assertRaises(ValueError):
            read_blocks(self.sample().replace('完整', '', 1).replace('BOOT', 'BOT', 1))

    def test_changed_raw_checksum_is_rejected(self):
        text = self.sample()
        check = re.search(r'\nCHECK=([A-F0-9]{8})', text)
        self.assertIsNotNone(check)
        altered = '00000001' if check[1] == '00000000' else '00000000'
        with self.assertRaises(ValueError):
            read_blocks(text[:check.start(1)] + altered + text[check.end(1):])


if __name__ == '__main__':
    unittest.main()
